# Generated by Django 3.1.1 on 2020-09-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('year', models.IntegerField()),
                ('poster', models.ImageField(upload_to='')),
                ('type', models.CharField(max_length=7, verbose_name=[('movie', 'movie'), ('series', 'series'), ('episode', 'episode')])),
            ],
        ),
    ]
