# Generated by Django 3.1.1 on 2020-09-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieitem',
            name='poster',
            field=models.URLField(),
        ),
    ]
